hostname: localhost
environment: development
server:
  address: "0.0.0.0"
  port: "3000"
  adminUsername: "username"
  adminPassword: "password"
geoapify:
  url: https://maps.geoapify.com/v1/staticmap
  key: caa37cc9e66847b1a08e477f8068d178
database:
  createDatabase: true
  connectionString: postgresql://postgres:password@localhost:5432
  params:
    dbname: cms_dev
    sslmode: disable
bucket:
  url: file:///Users/charlieegan/Code/photos/bucket
  webUrl: http://localhost:8000/bucket/
