baseURL: "https://photos.charlieegan3.com/"
languageCode: "en-us"
title: "Photo Gallery"
taxonomies:
  tag: "tags"
  location: "locations"
  archive: "archive"
menu:
  main:
  - name: "Latest"
    weight: 8
    url: "/"
  - name: "Tags"
    weight: 9
    url: "/tags/"
  - name: "Locations"
    weight: 10
    url: "/locations/"
  - name: "Calendar"
    weight: 11
    url: "/calendar/"
disableKinds:
  - RSS
  - Sitemap
params:
  map_image_size: 200
  small_grid_image_size: 300
  grid_image_size: 400
  single_image_size: 1080
  video_source: https://storage.googleapis.com/charlieegan3-instagram-archive/current/
  image_source: https://images.weserv.nl/?url=storage.googleapis.com/charlieegan3-instagram-archive/current/
