server:
  address: "0.0.0.0"
  port: "3000"
  adminUsername: "username"
  adminPassword: "password"
database:
  connection_string: postgresql://postgres:postgres@localhost:5432
  params:
    dbname: cms_test
    sslmode: disable
