server:
  address: "0.0.0.0"
  port: "3000"
  adminUsername: "username"
  adminPassword: "password"
database:
  createDatabase: true
  connectionString: postgresql://postgres:password@localhost:5432
  params:
    dbname: cms_dev
    sslmode: disable
bucket:
  url: file:///Users/charlieegan/Code/photos/cms/bucket
  webUrl: http://localhost:8000/bucket/
