name: Build Binary

on:
  release:
    types:
    - published
  workflow_dispatch:
    inputs: {}

jobs:
  refresh:
    name: build-binary
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        make -C cli get-binary

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["cli/photos"]'
