name: Build Site

on:
  push:
    branches: [ master ]

jobs:
  refresh:
    name: build-image
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run
      run: |
        ./hack/build_site.rb
