name: Build Binary

on:
  push:
    branches: [ master ]
    paths:
    - 'cli/**'
  workflow_dispatch:
    inputs: {}

jobs:
  refresh:
    name: build-binary
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        make -C cli get-binary

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: photos
        path: cli/photos
        if-no-files-found: error
