name: Build Binary

on:
  push:
    branches: [ master ]
    paths:
    - 'cli/**'
    - '.github/workflows/build.yaml'
  workflow_dispatch:
    inputs: {}

jobs:
  refresh:
    name: build-binary
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        make -C cli get-binary

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'cli/photos'
