name: Build Site

on:
  push:
    branches: [ master ]
    paths:
    - completed_json
    - locations
    - frontend
  workflow_dispatch:
    inputs: {}

jobs:
  refresh:
    name: build-site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        # this is needed to make force pushing retain history
        fetch-depth: 0

    - name: Download binary
      uses: charlieegan3/fetch-gh-release-asset@master
      with:
        file: "photos"
        target: "/usr/local/bin/photos"
        chmod_x: true

    - name: Run
      env:
        # TODO remove the need for these as able to use local dir alone for site cmds
        ENV_FILE: ${{ secrets.ENV_FILE }}
        GOOGLE_BUCKET: ${{ secrets.GOOGLE_BUCKET }}
        GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        PROXY_URL: ${{ secrets.PROXY_URL }}
        PROXY_TOKEN: ${{ secrets.PROXY_TOKEN }}
        GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        # source temp github token
        GIT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_COOKIE_STRING: ${{ secrets.INSTAGRAM_COOKIE_STRING }}
      run: |
        ./hack/build_site.rb
