name: Refresh

on:
  push:
    branches: [master]

jobs:
  refresh:
    name: Refresh
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
        GOOGLE_BUCKET: ${{ secrets.GOOGLE_BUCKET }}
        GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        PROXY_URL: ${{ secrets.PROXY_URL }}
        PROXY_TOKEN: ${{ secrets.PROXY_TOKEN }}
        GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_COOKIE_STRING: ${{ secrets.INSTAGRAM_COOKIE_STRING }}
      run: |
        cd cli

        make binary

        photos sync data
        photos sync locations
        photos sync media
