on:
  push:
    branches:
    - main

env:
  PACKAGE: github.com/charlieegan3/photos

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - run: |
        curl --fail -X POST https://api.github.com/repos/charlieegan3/${{ secrets.TOOLBELT_REPO }}/dispatches \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.TOOLBELT_UPDATE_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        --data '{"event_type": "update_deps", "client_payload": { "package": "${{env.PACKAGE}}", "commit": "${{github.sha}}" }}'
    - uses: actions/checkout@v3
